// GENERATED by tools/embed_catalog.py — DO NOT EDIT.
// Source of truth: localization/catalog/*.json
// Encoding: UTF-8 with BOM; compile with /utf-8.
#pragma once

struct Ex7LangStringEntry { unsigned int id; const wchar_t* text; };
struct Ex7LangTable {
    unsigned int lcid;
    const wchar_t* muiName;
    const Ex7LangStringEntry* entries;
    unsigned int count;
    const wchar_t* const* comments;  // unused, reserved
};

static const Ex7LangStringEntry g_strings_de[] = {
    { 5381, L"Zum Start&menü hinzufügen" },
    { 5382, L"Aus dem Start&menü entfernen" },
    { 5384, L"Fügt dem Startmenü eine Verknüpfung zu diesem Element hinzu" },
    { 5385, L"Entfernt die Verknüpfung zu diesem Element aus dem Startmenü" },
};

static const Ex7LangStringEntry g_strings_en[] = {
    { 5381, L"Add to the Start &menu" },
    { 5382, L"Remove from the Start &menu" },
    { 5384, L"Puts a shortcut to this item on the Start menu" },
    { 5385, L"Takes the shortcut for this item off the Start menu" },
};

static const Ex7LangStringEntry g_strings_fr[] = {
    { 5381, L"Ajouter au menu Démarr&er" },
    { 5382, L"Retirer du menu Démarr&er" },
    { 5384, L"Ajoute un raccourci vers cet élément dans le menu Démarrer" },
    { 5385, L"Enlève le raccourci vers cet élément du menu Démarrer" },
};

static const Ex7LangStringEntry g_strings_it[] = {
    { 5381, L"Aggiungi al menu &Start" },
    { 5382, L"Rimuovi dal menu &Start" },
    { 5384, L"Aggiunge un collegamento a questo elemento nel menu Start" },
    { 5385, L"Toglie il collegamento a questo elemento dal menu Start" },
};

static const Ex7LangStringEntry g_strings_ja[] = {
    { 5381, L"スタート メニューに追加(&S)" },
    { 5382, L"スタート メニューから削除(&S)" },
    { 5384, L"この項目へのショートカットをスタート メニューに追加します" },
    { 5385, L"この項目へのショートカットをスタート メニューから削除します" },
};

static const Ex7LangStringEntry g_strings_pl[] = {
    { 5381, L"Dodaj do menu &Start" },
    { 5382, L"Usuń z menu &Start" },
    { 5384, L"Umieszcza skrót do tego elementu w menu Start" },
    { 5385, L"Usuwa skrót do tego elementu z menu Start" },
};

static const Ex7LangStringEntry g_strings_pt_BR[] = {
    { 5381, L"Adicionar ao menu Inici&ar" },
    { 5382, L"Remover do menu Inici&ar" },
    { 5384, L"Adiciona um atalho a este item no menu Iniciar" },
    { 5385, L"Remove o atalho a este item do menu Iniciar" },
};

static const Ex7LangStringEntry g_strings_ru[] = {
    { 5381, L"Добавить в меню «&Пуск»" },
    { 5382, L"Удалить из меню «&Пуск»" },
    { 5384, L"Добавляет ярлык этого элемента в меню «Пуск»" },
    { 5385, L"Убирает ярлык этого элемента из меню «Пуск»" },
};

static const Ex7LangStringEntry g_strings_zh_CN[] = {
    { 5381, L"添加到“开始”菜单(&S)" },
    { 5382, L"从“开始”菜单删除(&S)" },
    { 5384, L"将此项目的快捷方式添加到“开始”菜单" },
    { 5385, L"将此项目的快捷方式从“开始”菜单中删除" },
};

static const Ex7LangStringEntry g_strings_es[] = {
    { 5381, L"Agregar al menú Inic&io" },
    { 5382, L"Quitar del menú Inic&io" },
    { 5384, L"Agrega un acceso directo a este elemento en el menú Inicio" },
    { 5385, L"Quita el acceso directo a este elemento del menú Inicio" },
};

static const Ex7LangTable g_ex7LangTables[] = {
    { 0x0407, L"de-DE", g_strings_de, sizeof(g_strings_de) / sizeof(g_strings_de[0]), nullptr },
    { 0x0409, L"en-US", g_strings_en, sizeof(g_strings_en) / sizeof(g_strings_en[0]), nullptr },
    { 0x040C, L"fr-FR", g_strings_fr, sizeof(g_strings_fr) / sizeof(g_strings_fr[0]), nullptr },
    { 0x0410, L"it-IT", g_strings_it, sizeof(g_strings_it) / sizeof(g_strings_it[0]), nullptr },
    { 0x0411, L"ja-JP", g_strings_ja, sizeof(g_strings_ja) / sizeof(g_strings_ja[0]), nullptr },
    { 0x0415, L"pl-PL", g_strings_pl, sizeof(g_strings_pl) / sizeof(g_strings_pl[0]), nullptr },
    { 0x0416, L"pt-BR", g_strings_pt_BR, sizeof(g_strings_pt_BR) / sizeof(g_strings_pt_BR[0]), nullptr },
    { 0x0419, L"ru-RU", g_strings_ru, sizeof(g_strings_ru) / sizeof(g_strings_ru[0]), nullptr },
    { 0x0804, L"zh-CN", g_strings_zh_CN, sizeof(g_strings_zh_CN) / sizeof(g_strings_zh_CN[0]), nullptr },
    { 0x0C0A, L"es-ES", g_strings_es, sizeof(g_strings_es) / sizeof(g_strings_es[0]), nullptr },
};
static const unsigned int g_ex7LangTableCount = sizeof(g_ex7LangTables) / sizeof(g_ex7LangTables[0]);
