// localizer.cpp — see localizer.h (v0.0.3: full resource-table rewrite with
// project-generated blobs; the .mui transplant was removed after failing
// real-world tests, and the in-place UpdateResource route was CI-proven
// unusable on the MU-marked LN binary — see header comments).
#include "localizer.h"

#include <windows.h>

#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <map>
#include <vector>

#include "lang_catalog.h"   // GENERATED by tools/embed_catalog.py
#include "winhash.h"
#include "importpatch.h"    // ComputePeChecksum

namespace ex7 {

extern void (*g_log)(const wchar_t* fmt, ...);
static void Log(const wchar_t* fmt, ...) {
    if (!g_log) return;
    va_list ap;
    va_start(ap, fmt);
    wchar_t buf[1024];
    _vsnwprintf_s(buf, _countof(buf), _TRUNCATE, fmt, ap);
    va_end(ap);
    g_log(L"%s", buf);
}

// ---------------- existing-resource enumeration ---------------------------
namespace {

struct ResName {
    bool isId = true;
    unsigned id = 0;             // when isId
    std::wstring str;            // when !isId
    LPCWSTR Ptr() const { return isId ? MAKEINTRESOURCEW(id) : str.c_str(); }
};

struct ResEntry {
    ResName type;
    ResName name;
    unsigned lang = 0;
    std::vector<unsigned char> bytes;
};

struct EnumCtx {
    HMODULE mod;
    std::vector<ResEntry>* out;
    std::vector<unsigned char>* muiSave;  // bytes of type "MUI" (id 1)
    bool ok = true;
};

EnumCtx* g_ctx = nullptr;  // EnumResource*W callbacks carry LPARAM; keep a
                           // single-instance context (tool is single-thread)

static bool SaveEntryBytes(const wchar_t* type, const wchar_t* name,
                           unsigned lang, ResName tn, ResName nn) {
    HRSRC r = FindResourceExW(g_ctx->mod, type, name, (WORD)lang);
    if (!r) { g_ctx->ok = false; return false; }
    HGLOBAL g = LoadResource(g_ctx->mod, r);
    DWORD sz = SizeofResource(g_ctx->mod, r);
    const unsigned char* p =
        g ? static_cast<const unsigned char*>(LockResource(g)) : nullptr;
    if (!p && sz) { g_ctx->ok = false; return false; }
    if (!tn.isId && tn.str == L"MUI") {
        // parked separately, re-added as "CUI" after the rewrite
        if (g_ctx->muiSave && g_ctx->muiSave->empty() && sz)
            g_ctx->muiSave->assign(p, p + sz);
        return true;
    }
    ResEntry e;
    e.type = tn; e.name = nn; e.lang = lang;
    e.bytes.assign(p, p + sz);
    g_ctx->out->push_back(e);
    return true;
}

BOOL CALLBACK EnumLangsCb(HMODULE, LPWSTR type, LPWSTR name, WORD lang,
                          LONG_PTR) {
    ResName tn, nn;
    if (IS_INTRESOURCE(type)) { tn.isId = true; tn.id = (unsigned)(uintptr_t)type; }
    else { tn.isId = false; tn.str = type; }
    if (IS_INTRESOURCE(name)) { nn.isId = true; nn.id = (unsigned)(uintptr_t)name; }
    else { nn.isId = false; nn.str = name; }
    return SaveEntryBytes(type, name, lang, tn, nn) ? TRUE : FALSE;
}

BOOL CALLBACK EnumNamesCb(HMODULE mod, LPWSTR type, LPWSTR name, LONG_PTR) {
    return EnumResourceLanguagesW(mod, type, name, EnumLangsCb, 0);
}

BOOL CALLBACK EnumTypesCb(HMODULE mod, LPWSTR type, LONG_PTR) {
    return EnumResourceNamesW(mod, type, EnumNamesCb, 0);
}

} // namespace

// -------------- full rewrite ----------------------------------------------

bool LocalizeWithGeneratedResources(const std::wstring& exePath,
                                    std::wstring& error) {
    // ---- 1. enumerate existing resources ---------------------------------
    HMODULE mod = LoadLibraryExW(exePath.c_str(), nullptr,
                                 LOAD_LIBRARY_AS_DATAFILE);
    if (!mod) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"LoadLibraryEx(datafile) failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    std::vector<ResEntry> entries;
    std::vector<unsigned char> muiSave;
    EnumCtx ctx{mod, &entries, &muiSave, true};
    g_ctx = &ctx;
    EnumResourceTypesW(mod, EnumTypesCb, 0);
    g_ctx = nullptr;
    FreeLibrary(mod);
    if (!ctx.ok) {
        error = L"failed to enumerate existing resources";
        return false;
    }
    Log(L"enumerated %u existing resources (MUI bytes parked: %u)",
        (unsigned)entries.size(), (unsigned)muiSave.size());

    // ---- 2+3+4. rewrite everything, add generated blobs, park CUI --------
    HANDLE h = BeginUpdateResourceW(exePath.c_str(), TRUE /* full rewrite */);
    if (!h) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"BeginUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    bool ok = true;
    auto fail = [&](const wchar_t* what, unsigned id, unsigned lang) {
        wchar_t buf[256];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"UpdateResource failed for %s %u (lcid 0x%04X), "
                     L"GetLastError=%u", what, id, lang, GetLastError());
        error = buf;
        ok = false;
    };

    unsigned copied = 0;
    for (const auto& e : entries) {
        if (!UpdateResourceW(h, e.type.Ptr(), e.name.Ptr(), (WORD)e.lang,
                             (LPVOID)e.bytes.data(), (DWORD)e.bytes.size())) {
            fail(e.type.isId ? L"copied-type" : e.type.str.c_str(),
                 e.name.isId ? e.name.id : 0, e.lang);
            break;
        }
        ++copied;
    }
    unsigned injected = 0;
    for (unsigned t = 0; t < g_ex7ResLangCount && ok; ++t) {
        const Ex7ResLang& lang = g_ex7ResLangs[t];
        for (unsigned i = 0; i < lang.blobCount; ++i) {
            const Ex7ResBlob& b = lang.blobs[i];
            if (!UpdateResourceW(h, MAKEINTRESOURCEW(b.type),
                                 MAKEINTRESOURCEW(b.id), (WORD)lang.lcid,
                                 (LPVOID)b.data, (DWORD)b.size)) {
                fail(L"generated", b.id, lang.lcid);
                break;
            }
            ++injected;
        }
    }
    if (ok && !muiSave.empty()) {
        if (!UpdateResourceW(h, L"CUI", MAKEINTRESOURCEW(1),
                             MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL),
                             (LPVOID)muiSave.data(), (DWORD)muiSave.size())) {
            fail(L"CUI", 1, 0);
        }
    }
    if (!EndUpdateResourceW(h, !ok /* discard on failure */)) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"EndUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    if (ok)
        Log(L"resource rewrite committed: %u preserved + %u generated "
            L"(%u languages) into %s%s", copied, injected, g_ex7ResLangCount,
            exePath.c_str(), muiSave.empty() ? L"" : L", MUI->CUI parked");
    return ok;
}

// -------------- PE checksum refresh ---------------------------------------

bool RefreshPeChecksum(const std::wstring& exePath, std::wstring& error) {
    HANDLE h = OpenForReadShared(exePath);
    if (h == INVALID_HANDLE_VALUE) {
        error = L"cannot open for checksum refresh";
        return false;
    }
    LARGE_INTEGER sz{};
    GetFileSizeEx(h, &sz);
    std::vector<uint8_t> image((size_t)sz.QuadPart);
    DWORD rd = 0;
    bool readOk = ReadFile(h, image.data(), (DWORD)image.size(), &rd,
                           nullptr) && rd == image.size();
    CloseHandle(h);
    if (!readOk || image.size() < 1024) {
        error = L"cannot read for checksum refresh";
        return false;
    }
    const unsigned char* p = image.data();
    if (p[0] != 'M' || p[1] != 'Z') { error = L"not a PE"; return false; }
    unsigned pe = p[0x3C] | (p[0x3D] << 8) | ((unsigned)p[0x3E] << 16) |
                  ((unsigned)p[0x3F] << 24);
    size_t optOff = pe + 24;
    size_t chkOff = optOff + 64;  // CheckSum in the optional header
    if (chkOff + 4 > image.size()) { error = L"PE too small"; return false; }
    memset(image.data() + chkOff, 0, 4);
    uint32_t sum = ComputePeChecksum(image, chkOff);
    image[chkOff + 0] = (uint8_t)(sum & 0xFF);
    image[chkOff + 1] = (uint8_t)((sum >> 8) & 0xFF);
    image[chkOff + 2] = (uint8_t)((sum >> 16) & 0xFF);
    image[chkOff + 3] = (uint8_t)((sum >> 24) & 0xFF);

    HANDLE w = CreateFileW(exePath.c_str(), GENERIC_WRITE, 0, nullptr,
                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (w == INVALID_HANDLE_VALUE) {
        error = L"cannot open for checksum write";
        return false;
    }
    LARGE_INTEGER off{};
    off.QuadPart = (LONGLONG)chkOff;
    SetFilePointerEx(w, off, nullptr, FILE_BEGIN);
    DWORD wr = 0;
    bool ok = WriteFile(w, image.data() + chkOff, 4, &wr, nullptr) && wr == 4;
    CloseHandle(w);
    if (!ok) { error = L"checksum write failed"; return false; }
    Log(L"refreshed PE CheckSum of %s", exePath.c_str());
    return true;
}

} // namespace ex7
