// localizer.h — on-machine injection of PROJECT-GENERATED resources.
//
// Architecture (v0.0.3): every UI resource the private explorer.exe copy
// needs (STRINGTABLE / MENU / DIALOGEX / ACCELERATOR) is built at PROJECT
// BUILD time by tools/build_resources.py from
//   - localization/catalog/<lang>.json            (our own texts)
//   - localization/templates/*.templates.json     (structure: ids, styles,
//                                                rects, class atoms, cmds)
// and embedded into this installer as raw byte blobs (lang_catalog.h,
// generated by tools/embed_catalog.py, fully round-trip validated).
// At install time they are committed into the private copy with
// BeginUpdateResource/UpdateResourceW — NOTHING is read from any Microsoft
// .mui file: no user-supplied reference, no EX7_REFERENCE_MUI, no identity
// check on external files, no symbol-server lookup for .mui (gone, removed).
//
// Failure policy (user directive 2026-09-28): STOP NET. Any build or
// injection failure aborts the whole setup with a hard error (exit 1); the
// resource update transaction is DISCARDED so the copy is never left in a
// half-localized state. There is intentionally no --allow-partial flag.
#pragma once

#include <string>
#include <vector>

namespace ex7 {

// PHASE 1 — deletes the "MUI" RCDATA type from `exePath` in its OWN commit.
// Root cause of v0.0.2's failure (CI repro run 36412428950): on the real
// Win7 explorer.exe — an MU-paired LN binary — UpdateResourceW refuses to
// add string resources with ERROR_NOT_SUPPORTED (50) while the file still
// carries the MUI marker. Removing the marker FIRST (separate transaction)
// takes the file out of MU pairing; only then are resource writes accepted.
// The original MUI bytes are returned via `savedBytes` when non-null, so
// RestoreAsCuiResource() can park them under the "CUI" type afterwards.
// Idempotent: when no MUI type exists, returns true with empty savedBytes.
bool NeutralizeMuiResource(const std::wstring& exePath,
                           std::vector<unsigned char>* savedBytes,
                           std::wstring& error);

// Injects every embedded language's resource blobs into `exePath` in ONE
// atomic update transaction. On any failure the transaction is discarded
// (the file keeps its previous bytes) and `error` describes the failing
// (type, id, lcid) entry plus GetLastError.
bool InjectGeneratedResources(const std::wstring& exePath, std::wstring& error);

// PHASE 3 — re-adds the saved MUI bytes under the "CUI" type (forensics /
// debuggability; the kernel MUI loader does not react to "CUI"). No-op when
// `bytes` is empty (MUI was not present).
bool RestoreAsCuiResource(const std::wstring& exePath,
                          const std::vector<unsigned char>& bytes,
                          std::wstring& error);

// Recomputes the PE optional-header CheckSum field after resource
// modification (MapFileAndCheckSum-compatible; the resource update makes
// the previous value stale). Non-fatal semantics are the caller's choice.
bool RefreshPeChecksum(const std::wstring& exePath, std::wstring& error);

} // namespace ex7
