// localizer.h — on-machine injection of PROJECT-GENERATED resources.
//
// Architecture (v0.0.3): every UI resource the private explorer.exe copy
// needs (STRINGTABLE / MENU / DIALOGEX / ACCELERATOR) is built at PROJECT
// BUILD time by tools/build_resources.py from
//   - localization/catalog/<lang>.json            (our own texts)
//   - localization/templates/*.templates.json     (structure: ids, styles,
//                                                rects, class atoms, cmds)
// and embedded into this installer as raw byte blobs (lang_catalog.h,
// generated by tools/embed_catalog.py, fully round-trip validated).
// At install time they are committed into the private copy with
// BeginUpdateResource/UpdateResourceW — NOTHING is read from any Microsoft
// .mui file: no user-supplied reference, no EX7_REFERENCE_MUI, no identity
// check on external files, no symbol-server lookup for .mui (gone, removed).
//
// Failure policy (user directive 2026-09-28): STOP NET. Any build or
// injection failure aborts the whole setup with a hard error (exit 1); the
// resource update transaction is DISCARDED so the copy is never left in a
// half-localized state. There is intentionally no --allow-partial flag.
#pragma once

#include <string>
#include <vector>

namespace ex7 {

// Injects every embedded language's resource blobs into `exePath` in ONE
// atomic update transaction. On any failure the transaction is discarded
// (the file keeps its previous bytes) and `error` describes the failing
// (type, id, lcid) entry plus GetLastError.
bool InjectGeneratedResources(const std::wstring& exePath, std::wstring& error);

// Renames the "MUI" RCDATA type to "CUI" inside `exePath`, so the kernel
// MUI loader stops looking for an external explorer.exe.mui next to the
// private copy (checksum pairing would otherwise reject everything).
// Required because ALL languages now come from blobs (full coverage), so
// there is no coverage gate anymore. If no MUI type exists the step is a
// no-op (logged) — reruns stay idempotent.
bool NeutralizeMuiResource(const std::wstring& exePath, std::wstring& error);

// Recomputes the PE optional-header CheckSum field after resource
// modification (MapFileAndCheckSum-compatible; the resource update makes
// the previous value stale). Non-fatal semantics are the caller's choice.
bool RefreshPeChecksum(const std::wstring& exePath, std::wstring& error);

} // namespace ex7
