// localizer.cpp — see localizer.h (v0.0.3: generated-blob injection only;
// the .mui transplant machinery was removed after failing real-world tests).
#include "localizer.h"

#include <windows.h>

#include <cstdio>
#include <cstring>
#include <vector>

#include "lang_catalog.h"   // GENERATED by tools/embed_catalog.py
#include "winhash.h"
#include "importpatch.h"    // ComputePeChecksum

namespace ex7 {

extern void (*g_log)(const wchar_t* fmt, ...);
static void Log(const wchar_t* fmt, ...) {
    if (!g_log) return;
    va_list ap;
    va_start(ap, fmt);
    wchar_t buf[1024];
    _vsnwprintf_s(buf, _countof(buf), _TRUNCATE, fmt, ap);
    va_end(ap);
    g_log(L"%s", buf);
}

bool InjectGeneratedResources(const std::wstring& exePath,
                              std::wstring& error) {
    // FALSE = keep every pre-existing resource of the private copy; we only
    // add/replace the exact (type, id, lcid) entries we write.
    HANDLE h = BeginUpdateResourceW(exePath.c_str(), FALSE);
    if (!h) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"BeginUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    bool ok = true;
    unsigned written = 0;
    for (unsigned t = 0; t < g_ex7ResLangCount && ok; ++t) {
        const Ex7ResLang& lang = g_ex7ResLangs[t];
        for (unsigned i = 0; i < lang.blobCount; ++i) {
            const Ex7ResBlob& b = lang.blobs[i];
            if (!UpdateResourceW(h, MAKEINTRESOURCEW(b.type),
                                 MAKEINTRESOURCEW(b.id), (WORD)lang.lcid,
                                 (LPVOID)b.data, (DWORD)b.size)) {
                wchar_t buf[256];
                _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                             L"UpdateResource failed for type %u id %u "
                             L"(lcid 0x%04X, %u bytes), GetLastError=%u",
                             b.type, b.id, lang.lcid, b.size,
                             GetLastError());
                error = buf;
                ok = false;
                break;
            }
            ++written;
        }
        if (ok)
            Log(L"injected %u generated resources for %ls (lcid 0x%04X)",
                lang.blobCount, lang.name, lang.lcid);
    }
    if (!EndUpdateResourceW(h, !ok /* discard on failure */)) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"EndUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    if (ok)
        Log(L"committed %u generated resources into %s", written,
            exePath.c_str());
    return ok;
}

// Reads the existing "MUI" resource bytes (so they can be re-added as "CUI").
static bool ReadMuiResourceBytes(const std::wstring& exePath,
                                 std::vector<unsigned char>& bytes,
                                 WORD& langOut) {
    HMODULE mod = LoadLibraryExW(exePath.c_str(), nullptr,
                                 LOAD_LIBRARY_AS_DATAFILE |
                                 LOAD_LIBRARY_AS_IMAGE_RESOURCE);
    if (!mod) return false;
    bool ok = false;
    HRSRC r = FindResourceExW(mod, L"MUI", MAKEINTRESOURCEW(1),
                              MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL));
    if (!r)
        r = FindResourceW(mod, MAKEINTRESOURCEW(1), L"MUI");
    if (r) {
        HGLOBAL g = LoadResource(mod, r);
        DWORD sz = SizeofResource(mod, r);
        if (g && sz) {
            const unsigned char* p =
                static_cast<const unsigned char*>(LockResource(g));
            bytes.assign(p, p + sz);
            ok = true;
        }
    }
    FreeLibrary(mod);
    langOut = MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL);
    return ok;
}

bool NeutralizeMuiResource(const std::wstring& exePath,
                           std::vector<unsigned char>* savedBytes,
                           std::wstring& error) {
    std::vector<unsigned char> bytes;
    WORD lang = 0;
    if (!ReadMuiResourceBytes(exePath, bytes, lang) || bytes.empty()) {
        Log(L"no MUI resource in %s (already neutralized?) — nothing to do",
            exePath.c_str());
        if (savedBytes) savedBytes->clear();
        return true;  // idempotent: absence is fine, all resources are ours
    }

    // Dedicated transaction per ERROR_NOT_SUPPORTED root cause (see .h):
    // delete the MU marker and COMMIT before touching anything else.
    HANDLE h = BeginUpdateResourceW(exePath.c_str(), FALSE);
    if (!h) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"BeginUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    if (!UpdateResourceW(h, L"MUI", MAKEINTRESOURCEW(1), lang, nullptr, 0)) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"failed to delete MUI resource, GetLastError=%u",
                     GetLastError());
        EndUpdateResourceW(h, TRUE);
        error = buf;
        return false;
    }
    if (!EndUpdateResourceW(h, FALSE)) {
        error = L"EndUpdateResource (MUI delete) failed";
        return false;
    }
    if (savedBytes) *savedBytes = bytes;
    Log(L"deleted MUI resource from %s (saved %u bytes, pending CUI)",
        exePath.c_str(), (unsigned)bytes.size());
    return true;
}

bool RestoreAsCuiResource(const std::wstring& exePath,
                          const std::vector<unsigned char>& bytes,
                          std::wstring& error) {
    if (bytes.empty()) return true;  // nothing was saved: nothing to restore
    HANDLE h = BeginUpdateResourceW(exePath.c_str(), FALSE);
    if (!h) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"BeginUpdateResource failed, GetLastError=%u",
                     GetLastError());
        error = buf;
        return false;
    }
    if (!UpdateResourceW(h, L"CUI", MAKEINTRESOURCEW(1),
                         MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL),
                         (LPVOID)bytes.data(), (DWORD)bytes.size())) {
        wchar_t buf[192];
        _snwprintf_s(buf, _countof(buf), _TRUNCATE,
                     L"failed to add CUI resource, GetLastError=%u",
                     GetLastError());
        EndUpdateResourceW(h, TRUE);
        error = buf;
        return false;
    }
    if (!EndUpdateResourceW(h, FALSE)) {
        error = L"EndUpdateResource (CUI add) failed";
        return false;
    }
    Log(L"parked MU marker bytes as CUI resource in %s", exePath.c_str());
    return true;
}

bool RefreshPeChecksum(const std::wstring& exePath, std::wstring& error) {
    HANDLE h = OpenForReadShared(exePath);
    if (h == INVALID_HANDLE_VALUE) {
        error = L"cannot open for checksum refresh";
        return false;
    }
    LARGE_INTEGER sz{};
    GetFileSizeEx(h, &sz);
    std::vector<uint8_t> image((size_t)sz.QuadPart);
    DWORD rd = 0;
    bool readOk = ReadFile(h, image.data(), (DWORD)image.size(), &rd,
                           nullptr) && rd == image.size();
    CloseHandle(h);
    if (!readOk || image.size() < 1024) {
        error = L"cannot read for checksum refresh";
        return false;
    }
    const unsigned char* p = image.data();
    if (p[0] != 'M' || p[1] != 'Z') { error = L"not a PE"; return false; }
    unsigned pe = p[0x3C] | (p[0x3D] << 8) | ((unsigned)p[0x3E] << 16) |
                  ((unsigned)p[0x3F] << 24);
    size_t optOff = pe + 24;
    size_t chkOff = optOff + 64;  // CheckSum in the optional header
    if (chkOff + 4 > image.size()) { error = L"PE too small"; return false; }
    memset(image.data() + chkOff, 0, 4);
    uint32_t sum = ComputePeChecksum(image, chkOff);
    image[chkOff + 0] = (uint8_t)(sum & 0xFF);
    image[chkOff + 1] = (uint8_t)((sum >> 8) & 0xFF);
    image[chkOff + 2] = (uint8_t)((sum >> 16) & 0xFF);
    image[chkOff + 3] = (uint8_t)((sum >> 24) & 0xFF);

    HANDLE w = CreateFileW(exePath.c_str(), GENERIC_WRITE, 0, nullptr,
                           OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (w == INVALID_HANDLE_VALUE) {
        error = L"cannot open for checksum write";
        return false;
    }
    LARGE_INTEGER off{};
    off.QuadPart = (LONGLONG)chkOff;
    SetFilePointerEx(w, off, nullptr, FILE_BEGIN);
    DWORD wr = 0;
    bool ok = WriteFile(w, image.data() + chkOff, 4, &wr, nullptr) && wr == 4;
    CloseHandle(w);
    if (!ok) { error = L"checksum write failed"; return false; }
    Log(L"refreshed PE CheckSum of %s", exePath.c_str());
    return true;
}

} // namespace ex7
