// localizer.h — on-machine injection of PROJECT-GENERATED resources via a
// FULL RESOURCE-TABLE REWRITE.
//
// Architecture (v0.0.3): every UI resource the private explorer.exe copy
// needs (STRINGTABLE / MENU / DIALOGEX / ACCELERATOR) is built at PROJECT
// BUILD time by tools/build_resources.py from
//   - localization/catalog/<lang>.json            (our own texts)
//   - localization/templates/*.templates.json     (structure: ids, styles,
//                                                rects, class atoms, cmds)
// and embedded into this installer as raw byte blobs (lang_catalog.h,
// generated by tools/embed_catalog.py, fully round-trip validated).
// NO Microsoft .mui is read, supplied or required anywhere — the old
// transplant, WIN7EXPLORERRESTORER_REFERENCE_MUI and the .mui identity pins are gone.
//
// WHY A FULL REWRITE (root cause of v0.0.2, CI-proven 2026-09-28, runs
// 36412428950 / 36415198307 / probe ci-logs/updres-36415591872):
//   * the real Win7 explorer.exe is an MU-paired LN binary;
//   * UpdateResourceW REFUSES to insert resources into it with
//     ERROR_NOT_SUPPORTED (50) — at every language (en-US/de-DE both fail);
//   * deleting the "MUI" type entry itself is refused with
//     ERROR_INVALID_PARAMETER (87);
//   * the supported route is BeginUpdateResource(bDeleteExistingResources=
//     TRUE): enumerate every existing resource (all types/names/languages),
//     rewrite them verbatim, skip "MUI", add our generated blobs, and park
//     the saved marker bytes under "CUI" — one atomic commit.
//
// Failure policy (user directive 2026-09-28): STOP NET. Any build or
// injection failure aborts the whole setup (exit 1); the update transaction
// is DISCARDED so the copy is never left in a half-localized state. There
// is intentionally no --allow-partial flag.
#pragma once

#include <string>
#include <vector>

namespace Win7ExplorerRestorer {

// Full atomic resource-table rewrite of `exePath`:
//   1. enumerate ALL existing resources (LoadLibraryEx AS_DATAFILE),
//      saving the "MUI" marker bytes aside;
//   2. BeginUpdateResource(deleteExisting = TRUE) and rewrite every
//      enumerated entry verbatim (skipping the "MUI" type);
//   3. write every embedded language blob at its (type, id, lcid)
//      coordinate (replaces any pre-existing injected entries on reruns —
//      idempotent) and park the saved marker bytes as "CUI";
//   4. EndUpdateResource(commit).
// On any failure the transaction is discarded (the file keeps its previous
// bytes and previous resource table) and `error` says which entry failed.
bool LocalizeWithGeneratedResources(const std::wstring& exePath,
                                    std::wstring& error);

// Recomputes the PE optional-header CheckSum field after resource
// modification (MapFileAndCheckSum-compatible; the resource rewrite makes
// the previous value stale).
bool RefreshPeChecksum(const std::wstring& exePath, std::wstring& error);

} // namespace Win7ExplorerRestorer
