#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
embed_catalog.py — turns localization/catalog/*.json into build artifacts:

  1. installer/ex7selfcontained/lang_catalog.h
     C++ tables used by the localizer to inject string resources into the
     private explorer.exe copy (and available for future MENU/DIALOG
     resources once localization/constraints/explorer.exe.constraints.json
     exists).

  2. explorerwrapper/ex7_languages.rc
     Multilingual STRINGTABLE for the wrapper's own resources. The existing
     fallback in StartMenuPin.cpp (LoadStringW(g_hInstance, ...)) then
     serves every catalog language automatically — no .mui file needed for
     shell32 at all. (File must be ADDED to explorerwrapper.vcxproj; the
     generator patches the project file when run with --patch-vcxproj.)

The generator is deterministic: same catalog -> same output bytes.
It runs tools/verify_catalog.py first and refuses to emit on errors.
Output encoding: UTF-8 with BOM (compile the installer with /utf-8; rc.exe
reads the .rc with its default UTF-8/UTF-16 handling).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.verify_catalog import verify  # noqa: E402


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def gen_header(catalogs: dict) -> str:
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Source of truth: localization/catalog/*.json",
        "// Encoding: UTF-8 with BOM; compile with /utf-8.",
        "#pragma once",
        "",
        "struct Ex7LangStringEntry { unsigned int id; const wchar_t* text; };",
        "struct Ex7LangTable {",
        "    unsigned int lcid;",
        "    const wchar_t* muiName;",
        "    const Ex7LangStringEntry* entries;",
        "    unsigned int count;",
        "    const wchar_t* const* comments;  // unused, reserved",
        "};",
        "",
    ]
    tables = []
    for lang in sorted(catalogs, key=lambda k: catalogs[k]["language"]["lcid"]):
        data = catalogs[lang]
        meta = data["language"]
        var = "g_strings_" + lang.replace("-", "_")
        out.append(f"static const Ex7LangStringEntry {var}[] = {{")
        for sid in sorted(data["strings"], key=int):
            text = c_escape(data["strings"][sid])
            out.append(f'    {{ {sid}, L"{text}" }},')
        out.append("};")
        out.append("")
        tables.append(
            f'    {{ {meta["lcid"]}, L"{meta["mui_name"]}", {var}, '
            f'sizeof({var}) / sizeof({var}[0]), nullptr }},')
    out.append("static const Ex7LangTable g_ex7LangTables[] = {")
    out.extend(tables)
    out.append("};")
    out.append("static const unsigned int g_ex7LangTableCount = "
               "sizeof(g_ex7LangTables) / sizeof(g_ex7LangTables[0]);")
    out.append("")
    return "\n".join(out)


def gen_rc(catalogs: dict) -> str:
    # RC numeric language IDs come straight from the catalog (1:1 with LCID).
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Multilingual string resources for the wrapper fallback path",
        "// (StartMenuPin.cpp -> LoadStringW(g_hInstance, ...)).",
        "#include <windows.h>",
        "",
    ]
    for lang in sorted(catalogs, key=lambda k: catalogs[k]["language"]["lcid"]):
        data = catalogs[lang]
        lcid = int(data["language"]["lcid"], 16)
        prim, sub = lcid & 0x3FF, lcid >> 10
        out.append(f"// {data['language'].get('name', lang)} ({lang})")
        out.append("STRINGTABLE")
        out.append(f"LANGUAGE {prim}, {sub}")
        out.append("{")
        for sid in sorted(data["strings"], key=int):
            text = c_escape(data["strings"][sid]).replace("'", "''")
            out.append(f'    {sid}, "{text}"')
        out.append("}")
        out.append("")
    return "\n".join(out)


def load_catalogs(catdir: Path) -> dict:
    out = {}
    for f in sorted(catdir.glob("*.json")):
        data = json.loads(f.read_text(encoding="utf-8"))
        out[data["language"]["id"]] = data
    return out


def patch_vcxproj(rc_rel: str = "ex7_languages.rc") -> bool:
    vcx = ROOT / "explorerwrapper" / "explorerwrapper.vcxproj"
    text = vcx.read_text(encoding="utf-8")
    if rc_rel in text:
        print("vcxproj already references the .rc; nothing to do")
        return False
    marker = "<ClCompile Include="
    idx = text.rfind("</ItemGroup>")
    if idx == -1:
        raise RuntimeError("vcxproj: cannot find an ItemGroup to extend")
    insert = f'  <ItemGroup>\n    <ResourceCompile Include="{rc_rel}" />\n  </ItemGroup>\n'
    vcx.write_text(text[:idx] + insert + text[idx:], encoding="utf-8")
    print(f"vcxproj patched: added {rc_rel}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog-dir", default=str(ROOT / "localization" / "catalog"))
    ap.add_argument("--constraints", action="append",
                    default=[str(ROOT / "localization" / "constraints"
                                 / "shell32.dll.constraints.json")])
    ap.add_argument("--patch-vcxproj", action="store_true")
    args = ap.parse_args()

    code = verify(Path(args.catalog_dir), args.constraints)
    if code != 0:
        print("embed_catalog: catalog verification failed; not emitting", file=sys.stderr)
        return code

    catalogs = load_catalogs(Path(args.catalog_dir))

    hdr = ROOT / "installer" / "ex7selfcontained" / "lang_catalog.h"
    hdr.parent.mkdir(parents=True, exist_ok=True)
    hdr.write_bytes(b"\xef\xbb\xbf" + gen_header(catalogs).encode("utf-8"))
    print(f"written {hdr}")

    rc = ROOT / "explorerwrapper" / "ex7_languages.rc"
    rc.write_bytes(b"\xef\xbb\xbf" + gen_rc(catalogs).encode("utf-8"))
    print(f"written {rc}")

    if args.patch_vcxproj:
        patch_vcxproj()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
