#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
embed_catalog.py — turns the repo localization sources into build artifacts:

  1. installer/ex7selfcontained/lang_catalog.h
     PRE-BUILT PE resource payloads (STRINGTABLE / MENU / DIALOGEX /
     ACCELERATOR byte blobs) produced by tools/build_resources.py from
     localization/catalog/*.json (texts) + localization/templates/
     explorer.exe.templates.json (structure). The installer injects them
     into the private explorer.exe copy — no external .mui is ever read.

  2. explorerwrapper/ex7_languages.rc
     Multilingual STRINGTABLE for the wrapper's own resources. The existing
     fallback in StartMenuPin.cpp (LoadStringW(g_hInstance, ...)) then
     serves every catalog language automatically — no .mui file needed for
     shell32 at all. (File must be ADDED to explorerwrapper.vcxproj; the
     generator patches the project file when run with --patch-vcxproj.)

The generator is deterministic: same catalog -> same output bytes.
It runs tools/verify_catalog.py first and refuses to emit on errors;
build_resources then round-trip validates EVERY payload (parses the
generated bytes back and diffs structure+text) and aborts on mismatch.
Output encoding: UTF-8 with BOM (compile the installer with /utf-8; rc.exe
reads the .rc with its default UTF-8/UTF-16 handling).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.verify_catalog import verify  # noqa: E402
from tools.build_resources import build_all, BuildError  # noqa: E402


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _enum_key(dkey: str):
    rid, _, lang = dkey.partition("/")
    return int(rid), int(lang.split(":")[1], 16)


def _ctl_key_fields(key: str):
    if "#" in key:
        cid, occ = key.rsplit("#", 1)
        return int(cid), int(occ)
    return int(key), 1


def gen_header(catalogs: dict, templates: dict, explorer_ids: set) -> str:
    """Emits PRE-BUILT resource payloads (validated by build_resources)."""
    payloads = build_all(catalogs, templates, explorer_ids)
    if not payloads:
        raise BuildError("no language produced resource payloads")
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Sources: localization/catalog/*.json (texts) +",
        "//          localization/templates/explorer.exe.templates.json (structure).",
        "// Every payload round-trip validated by tools/build_resources.py.",
        "// Encoding: UTF-8 with BOM; compile with /utf-8.",
        "#pragma once",
        "",
        "// One PE-resource payload (type = RT_MENU 4, RT_DIALOG 5,",
        "// RT_STRING 6, RT_ACCELERATOR 9) ready for UpdateResourceW.",
        "struct Ex7ResBlob { unsigned int type; unsigned int id;",
        "                    const unsigned char* data; unsigned int size; };",
        "struct Ex7ResLang { unsigned int lcid; const wchar_t* name;",
        "                    const Ex7ResBlob* blobs; unsigned int blobCount; };",
        "",
    ]
    tables = []
    for lang in sorted(payloads,
                       key=lambda k: 0 if k == "en" else 1):  # en = fallback first
        data = catalogs[lang]
        meta = data["language"]
        safe = lang.replace("-", "_")
        blob_entries = []
        for i, b in enumerate(sorted(payloads[lang],
                                     key=lambda x: (x["type"], x["resId"]))):
            bvar = f"g_res_{safe}_{i:03d}"
            raw = b["payload"]
            lines = []
            for off in range(0, len(raw), 16):
                chunk = raw[off:off + 16]
                lines.append("    " + " ".join(f"0x{v:02X}," for v in chunk))
            out.append(f"static const unsigned char {bvar}[] = {{")
            out.extend(lines)
            out.append("};")
            blob_entries.append(
                f"    {{ {b['type']}, {b['resId']}, {bvar}, sizeof({bvar}) }},")
        btab = f"g_blobs_{safe}"
        out.append(f"static const Ex7ResBlob {btab}[] = {{")
        out.extend(blob_entries)
        out.append("};")
        out.append("")
        lcid = int(str(meta["lcid"]), 16)
        tables.append(
            f'    {{ 0x{lcid:04X}, L"{c_escape(meta["mui_name"])}", '
            f'{btab}, sizeof({btab}) / sizeof({btab}[0]) }},')
    out.append("static const Ex7ResLang g_ex7ResLangs[] = {")
    out.extend(tables)
    out.append("};")
    out.append("static const unsigned int g_ex7ResLangCount = "
               "sizeof(g_ex7ResLangs) / sizeof(g_ex7ResLangs[0]);")
    out.append("")
    return "\n".join(out)


def gen_rc(catalogs: dict) -> str:
    # RC numeric language IDs come straight from the catalog (1:1 with LCID).
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Multilingual string resources for the wrapper fallback path",
        "// (StartMenuPin.cpp -> LoadStringW(g_hInstance, ...)).",
        "#include <windows.h>",
        "",
    ]
    for lang in sorted(catalogs, key=lambda k: catalogs[k]["language"]["lcid"]):
        data = catalogs[lang]
        lcid = int(data["language"]["lcid"], 16)
        prim, sub = lcid & 0x3FF, lcid >> 10
        out.append(f"// {data['language'].get('name', lang)} ({lang})")
        out.append("STRINGTABLE")
        out.append(f"LANGUAGE {prim}, {sub}")
        out.append("{")
        for sid in sorted(data["strings"], key=int):
            text = c_escape(data["strings"][sid]).replace("'", "''")
            out.append(f'    {sid}, "{text}"')
        out.append("}")
        out.append("")
    return "\n".join(out)


def load_catalogs(catdir: Path) -> dict:
    out = {}
    for f in sorted(catdir.glob("*.json")):
        data = json.loads(f.read_text(encoding="utf-8"))
        out[data["language"]["id"]] = data
    return out


def patch_vcxproj(rc_rel: str = "ex7_languages.rc") -> bool:
    vcx = ROOT / "explorerwrapper" / "explorerwrapper.vcxproj"
    text = vcx.read_text(encoding="utf-8")
    if rc_rel in text:
        print("vcxproj already references the .rc; nothing to do")
        return False
    marker = "<ClCompile Include="
    idx = text.rfind("</ItemGroup>")
    if idx == -1:
        raise RuntimeError("vcxproj: cannot find an ItemGroup to extend")
    insert = f'  <ItemGroup>\n    <ResourceCompile Include="{rc_rel}" />\n  </ItemGroup>\n'
    vcx.write_text(text[:idx] + insert + text[idx:], encoding="utf-8")
    print(f"vcxproj patched: added {rc_rel}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog-dir", default=str(ROOT / "localization" / "catalog"))
    ap.add_argument("--constraints", action="append",
                    default=[str(ROOT / "localization" / "constraints"
                                 / "shell32.dll.constraints.json"),
                             str(ROOT / "localization" / "constraints"
                                 / "explorer.exe.constraints.json")])
    ap.add_argument("--patch-vcxproj", action="store_true")
    args = ap.parse_args()

    code = verify(Path(args.catalog_dir), args.constraints)
    if code != 0:
        print("embed_catalog: catalog verification failed; not emitting", file=sys.stderr)
        return code

    catalogs = load_catalogs(Path(args.catalog_dir))

    explorer_ids = set()
    for cpath in args.constraints:
        c = json.loads(Path(cpath).read_text(encoding="utf-8"))
        if "explorer.exe" in Path(cpath).name:
            explorer_ids |= set(int(k) for k in c.get("strings", {}))

    tpl_path = ROOT / "localization" / "templates" / "explorer.exe.templates.json"
    templates = json.loads(tpl_path.read_text(encoding="utf-8"))

    try:
        header = gen_header(catalogs, templates, explorer_ids)
    except BuildError as exc:
        print(f"embed_catalog: resource build FAILED: {exc}", file=sys.stderr)
        return 3

    hdr = ROOT / "installer" / "ex7selfcontained" / "lang_catalog.h"
    hdr.parent.mkdir(parents=True, exist_ok=True)
    hdr.write_bytes(b"\xef\xbb\xbf" + header.encode("utf-8"))
    print(f"written {hdr}")

    rc = ROOT / "explorerwrapper" / "ex7_languages.rc"
    # rc.exe accetta in modo affidabile i file .rc in UTF-16LE con BOM
    # (UTF-8 fallisce su runner MSVC: è la stessa codifica di wrapper.rc).
    rc.write_bytes(gen_rc(catalogs).encode("utf-16"))
    print(f"written {rc}")

    if args.patch_vcxproj:
        patch_vcxproj()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
