#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
embed_catalog.py — turns localization/catalog/*.json into build artifacts:

  1. installer/ex7selfcontained/lang_catalog.h
     C++ tables used by the localizer to inject string resources into the
     private explorer.exe copy (and available for future MENU/DIALOG
     resources once localization/constraints/explorer.exe.constraints.json
     exists).

  2. explorerwrapper/ex7_languages.rc
     Multilingual STRINGTABLE for the wrapper's own resources. The existing
     fallback in StartMenuPin.cpp (LoadStringW(g_hInstance, ...)) then
     serves every catalog language automatically — no .mui file needed for
     shell32 at all. (File must be ADDED to explorerwrapper.vcxproj; the
     generator patches the project file when run with --patch-vcxproj.)

The generator is deterministic: same catalog -> same output bytes.
It runs tools/verify_catalog.py first and refuses to emit on errors.
Output encoding: UTF-8 with BOM (compile the installer with /utf-8; rc.exe
reads the .rc with its default UTF-8/UTF-16 handling).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tools.verify_catalog import verify  # noqa: E402


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _enum_key(dkey: str):
    rid, _, lang = dkey.partition("/")
    return int(rid), int(lang.split(":")[1], 16)


def _ctl_key_fields(key: str):
    if "#" in key:
        cid, occ = key.rsplit("#", 1)
        return int(cid), int(occ)
    return int(key), 1


def gen_header(catalogs: dict, explorer_ids=None) -> str:
    explorer_ids = explorer_ids or set()
    explorer_dialogs = 6
    explorer_menus = 6
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Source of truth: localization/catalog/*.json",
        "// Encoding: UTF-8 with BOM; compile with /utf-8.",
        "#pragma once",
        "",
        "struct Ex7LangStringEntry { unsigned int id; const wchar_t* text; };",
        "struct Ex7LangDlgCtl { unsigned int id; unsigned int occurrence; const wchar_t* text; };",
        "struct Ex7LangDialog { unsigned int resId; unsigned int lang; const wchar_t* title; const Ex7LangDlgCtl* ctls; unsigned int ctlCount; };",
        "struct Ex7LangMenuItem { unsigned int level; unsigned int index; const wchar_t* text; };",
        "struct Ex7LangMenu { unsigned int resId; unsigned int lang; const Ex7LangMenuItem* items; unsigned int itemCount; };",
        "struct Ex7LangTable {",
        "    unsigned int lcid;",
        "    const wchar_t* muiName;",
        "    const Ex7LangStringEntry* entries;",
        "    unsigned int count;",
        "    const Ex7LangDialog* dialogs;",
        "    unsigned int dialogCount;",
        "    const Ex7LangMenu* menus;",
        "    unsigned int menuCount;",
        "    unsigned int hasFullExplorer;  // 1 se copre ogni id/menu/dialog di explorer.exe.mui",
        "    const wchar_t* const* comments;  // unused, reserved",
        "};",
        "",
    ]
    tables = []
    for lang in sorted(catalogs, key=lambda k: catalogs[k]["language"]["lcid"]):
        data = catalogs[lang]
        meta = data["language"]
        safe = lang.replace("-", "_")
        var = "g_strings_" + safe
        out.append(f"static const Ex7LangStringEntry {var}[] = {{")
        for sid in sorted(data["strings"], key=int):
            text = c_escape(data["strings"][sid])
            out.append(f'    {{ {sid}, L"{text}" }},')
        out.append("};")
        out.append("")

        dlg_vars = []
        for dkey in sorted(data.get("dialogs", {}), key=_enum_key):
            rid, dlang = _enum_key(dkey)
            dentry = data["dialogs"][dkey]
            ctls = dentry.get("controls", {})
            cvar = f"g_dlgctls_{safe}_{rid}_{dlang:04x}"
            out.append(f"static const Ex7LangDlgCtl {cvar}[] = {{")
            for ckey in sorted(ctls, key=_ctl_key_fields):
                cid, occ = _ctl_key_fields(ckey)
                out.append(f'    {{ {cid}, {occ}, L"{c_escape(ctls[ckey])}" }},')
            out.append("};")
            title = dentry.get("title")
            tlit = "nullptr" if title is None else f'L"{c_escape(title)}"'
            dlg_vars.append((rid, dlang, tlit, cvar, len(ctls)))
        dvar = "g_dialogs_" + safe
        if dlg_vars:
            out.append(f"static const Ex7LangDialog {dvar}[] = {{")
            for rid, dlang, tlit, cvar, cnt in dlg_vars:
                out.append(f"    {{ {rid}, 0x{dlang:04X}, {tlit}, {cvar}, {cnt} }},")
            out.append("};")
            out.append("")
        else:
            dvar = "nullptr"

        menu_vars = []
        for mkey in sorted(data.get("menus", {}), key=_enum_key):
            rid, mlang = _enum_key(mkey)
            ivar = f"g_menuitems_{safe}_{rid}_{mlang:04x}"
            items = data["menus"][mkey]
            out.append(f"static const Ex7LangMenuItem {ivar}[] = {{")
            for ikey in sorted(items, key=lambda k: tuple(int(x) for x in k.split("/"))):
                li, ii = (int(x) for x in ikey.split("/"))
                out.append(f'    {{ {li}, {ii}, L"{c_escape(items[ikey])}" }},')
            out.append("};")
            menu_vars.append((rid, mlang, ivar, len(items)))
        mvar = "g_menus_" + safe
        if menu_vars:
            out.append(f"static const Ex7LangMenu {mvar}[] = {{")
            for rid, mlang, ivar, cnt in menu_vars:
                out.append(f"    {{ {rid}, 0x{mlang:04X}, {ivar}, {cnt} }},")
            out.append("};")
            out.append("")
        else:
            mvar = "nullptr"

        has_full = 0
        if explorer_ids:
            cov = all(sid in data["strings"] for sid in explorer_ids)
            has_full = int(cov
                         and len(data.get("dialogs", {})) >= explorer_dialogs
                         and len(data.get("menus", {})) >= explorer_menus)

        dcount = f"sizeof({dvar}) / sizeof({dvar}[0])" if dvar != "nullptr" else "0"
        mcount = f"sizeof({mvar}) / sizeof({mvar}[0])" if mvar != "nullptr" else "0"
        tables.append(
            f'    {{ {meta["lcid"]}, L"{meta["mui_name"]}", {var}, '
            f'sizeof({var}) / sizeof({var}[0]), {dvar}, {dcount}, '
            f'{mvar}, {mcount}, {has_full}, nullptr }},')
    out.append("static const Ex7LangTable g_ex7LangTables[] = {")
    out.extend(tables)
    out.append("};")
    out.append("static const unsigned int g_ex7LangTableCount = "
               "sizeof(g_ex7LangTables) / sizeof(g_ex7LangTables[0]);")
    out.append("")
    return "\n".join(out)


def gen_rc(catalogs: dict) -> str:
    # RC numeric language IDs come straight from the catalog (1:1 with LCID).
    out = [
        "// GENERATED by tools/embed_catalog.py — DO NOT EDIT.",
        "// Multilingual string resources for the wrapper fallback path",
        "// (StartMenuPin.cpp -> LoadStringW(g_hInstance, ...)).",
        "#include <windows.h>",
        "",
    ]
    for lang in sorted(catalogs, key=lambda k: catalogs[k]["language"]["lcid"]):
        data = catalogs[lang]
        lcid = int(data["language"]["lcid"], 16)
        prim, sub = lcid & 0x3FF, lcid >> 10
        out.append(f"// {data['language'].get('name', lang)} ({lang})")
        out.append("STRINGTABLE")
        out.append(f"LANGUAGE {prim}, {sub}")
        out.append("{")
        for sid in sorted(data["strings"], key=int):
            text = c_escape(data["strings"][sid]).replace("'", "''")
            out.append(f'    {sid}, "{text}"')
        out.append("}")
        out.append("")
    return "\n".join(out)


def load_catalogs(catdir: Path) -> dict:
    out = {}
    for f in sorted(catdir.glob("*.json")):
        data = json.loads(f.read_text(encoding="utf-8"))
        out[data["language"]["id"]] = data
    return out


def patch_vcxproj(rc_rel: str = "ex7_languages.rc") -> bool:
    vcx = ROOT / "explorerwrapper" / "explorerwrapper.vcxproj"
    text = vcx.read_text(encoding="utf-8")
    if rc_rel in text:
        print("vcxproj already references the .rc; nothing to do")
        return False
    marker = "<ClCompile Include="
    idx = text.rfind("</ItemGroup>")
    if idx == -1:
        raise RuntimeError("vcxproj: cannot find an ItemGroup to extend")
    insert = f'  <ItemGroup>\n    <ResourceCompile Include="{rc_rel}" />\n  </ItemGroup>\n'
    vcx.write_text(text[:idx] + insert + text[idx:], encoding="utf-8")
    print(f"vcxproj patched: added {rc_rel}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog-dir", default=str(ROOT / "localization" / "catalog"))
    ap.add_argument("--constraints", action="append",
                    default=[str(ROOT / "localization" / "constraints"
                                 / "shell32.dll.constraints.json"),
                             str(ROOT / "localization" / "constraints"
                                 / "explorer.exe.constraints.json")])
    ap.add_argument("--patch-vcxproj", action="store_true")
    args = ap.parse_args()

    code = verify(Path(args.catalog_dir), args.constraints)
    if code != 0:
        print("embed_catalog: catalog verification failed; not emitting", file=sys.stderr)
        return code

    catalogs = load_catalogs(Path(args.catalog_dir))

    explorer_ids = set()
    for cpath in args.constraints:
        c = json.loads(Path(cpath).read_text(encoding="utf-8"))
        if "explorer.exe" in Path(cpath).name:
            explorer_ids |= set(c.get("strings", {}))

    hdr = ROOT / "installer" / "ex7selfcontained" / "lang_catalog.h"
    hdr.parent.mkdir(parents=True, exist_ok=True)
    hdr.write_bytes(b"\xef\xbb\xbf" + gen_header(catalogs, explorer_ids).encode("utf-8"))
    print(f"written {hdr}")

    rc = ROOT / "explorerwrapper" / "ex7_languages.rc"
    # rc.exe accetta in modo affidabile i file .rc in UTF-16LE con BOM
    # (UTF-8 fallisce su runner MSVC: è la stessa codifica di wrapper.rc).
    rc.write_bytes(gen_rc(catalogs).encode("utf-16"))
    print(f"written {rc}")

    if args.patch_vcxproj:
        patch_vcxproj()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
